@AIMentor_HostAddress = http://localhost:5285

POST {{AIMentor_HostAddress}}/sessions/0/messages
Accept: application/json
Content-Type: application/json

{
  "content": "Hello, how are you?"
}

###

GET {{AIMentor_HostAddress}}/todos/1
Accept: application/json

###
