@AIMentor_HostAddress = http://localhost:5285

POST {{AIMentor_HostAddress}}/sessions/7/messages
Accept: application/json
Content-Type: application/json

{
  "content": "Tell last names of all persons we've mentioned in the dialogue"
}

###

GET {{AIMentor_HostAddress}}/todos/1
Accept: application/json

###
